# 基本は github.com のレポジトリーを指定するだけ
[[plugins]]
repo = 'Shougo/dein.vim'
# [[plugins]]
# repo = 'gmarik/vundle'
[[plugins]]
repo = "mattn/sonictemplate-vim"
[[plugins]]
repo = 'scrooloose/syntastic'
[[plugins]]
repo = 'nathanaelkane/vim-indent-guides'
[[plugins]]
repo = 'Shougo/neosnippet'
[[plugins]]
repo = 'Shougo/neosnippet-snippets'
# [[plugins]]
# repo = "Shougo/tabpagebuffer.vim"
# [[plugins]]
# repo = 'Shougo/vimfiler'
[[plugins]]
repo = 'rking/ag.vim'
[[plugins]]
repo = 'tyru/caw.vim.git'
[[plugins]]
repo = 'thinca/vim-qfreplace'
[[plugins]]
repo = 'szw/vim-tags'
[[plugins]]
repo = 'kana/vim-fakeclip'
[[plugins]]
repo = 'mbbill/undotree'
[[plugins]]
# repo = 'YankRing.vim'
repo = 'LeafCage/yankround.vim'
# [[plugins]]
# repo = 'kien/ctrlp.vim'
[[plugins]]
repo = 'tpope/vim-surround'
[[plugins]]
repo = 'tpope/vim-endwise'
[[plugins]]
repo = 'tpope/vim-fugitive'
[[plugins]]
repo = 'mattn/webapi-vim'
[[plugins]]
repo = 'Konfekt/FastFold'
[[plugins]]
repo = 'terryma/vim-multiple-cursors'
[[plugins]]
repo = 'haya14busa/incsearch.vim'
[[plugins]]
repo = 'easymotion/vim-easymotion'
